import json
import base64
import asyncio
from solana.rpc.async_api import AsyncClient
from solders.keypair import Keypair
from solders.transaction import Transaction

# Use the same wallet we generated in setup
KEYPAIR_FILE = "test_wallet.json"
RPC_URL = "https://api.devnet.solana.com"

async def sign_and_broadcast(base64_txs: list[str]):
    client = AsyncClient(RPC_URL)
    try:
        # 1. Load the Notary (Your Private Key)
        with open(KEYPAIR_FILE, 'r') as f:
            secret_key_list = json.load(f)
            # Convert list of integers to bytes
            signer = Keypair.from_bytes(bytes(secret_key_list))
        print(f"✍️ Signing with: {signer.pubkey()}")

        for i, b64_str in enumerate(base64_txs):
            # 2. Decode the Agent's output
            raw_tx = base64.b64decode(b64_str)
            
            # 3. Reconstruct and Sign
            # Note: We use from_bytes for the wire-format transaction
            tx = Transaction.from_bytes(raw_tx)
            
            # Update the blockhash before sending, as it might have changed since building
            latest_blockhash_resp = await client.get_latest_blockhash()
            tx.recent_blockhash = latest_blockhash_resp.value.blockhash

            # Sign the transaction with the loaded keypair
            tx.sign(signer)
            
            print(f"🔄 Broadcasting Transaction {i+1}...")
            try:
                # send_raw_transaction is used when we have a fully signed tx
                sig = await client.send_raw_transaction(bytes(tx))
                await client.confirm_transaction(sig.value)
                print(f"✅ SUCCESS! Rent Recovered. Signature: {sig.value}")
                print(f"🔗 View on Solscan: https://solscan.io/tx/{sig.value}?cluster=devnet")
            except Exception as e:
                print(f"❌ Failed to broadcast Transaction {i+1}: {e}")
    finally:
        await client.close()

if __name__ == "__main__":
    # You will paste the Base64 string generated by solzzt.py here
    # Example:
    # tx_from_agent = ["AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..."]
    tx_from_agent = [] # Placeholder for agent output
    print("🚀 Ready to sign. Waiting for Agent output (paste into tx_from_agent list in this file)...")
    # For manual testing, uncomment the line below and populate tx_from_agent
    # asyncio.run(sign_and_broadcast(tx_from_agent))