import pytest
import asyncio
from solders.pubkey import Pubkey
from solana.rpc.async_api import AsyncClient

# Import the classes we want to test
from app.sniffer import Sniffer

# --- Configuration ---
# Use the reliable Helius Devnet RPC for testing
RPC_URL = "https://devnet.helius-rpc.com/?api-key=929876d8-c714-47d1-a1d4-6541ac589e56"

# --- Pytest Fixture for Async Client ---
# This sets up and tears down the RPC client for our tests
@pytest.fixture(scope="module")
async def async_client():
    client = AsyncClient(RPC_URL)
    yield client
    await client.close()

# --- Test Case 1: A Known Clean Wallet ---
@pytest.mark.asyncio
async def test_sniff_clean_wallet(async_client: AsyncClient):
    """
    Tests the Sniffer against a Solana wallet known to have NO zombie or dust accounts.
    This wallet is the official System Program ID, which by definition cannot own SPL tokens.
    """
    print("\n--- Running Test: Clean Wallet ---")
    
    # ARRANGE: Set up the test conditions
    # The System Program ID is a perfect example of a "clean" wallet for this test
    clean_wallet_pubkey = Pubkey.from_string("11111111111111111111111111111111")
    sniffer = Sniffer(async_client, RPC_URL)

    # ACT: Perform the action we are testing
    results = await sniffer.sniff_accounts(clean_wallet_pubkey)

    # ASSERT: Verify that the outcome is as expected
    assert results is not None, "Sniffer should return a result object, not None"
    assert isinstance(results.get("zombies"), list), "Zombies should be a list"
    assert isinstance(results.get("dust"), list), "Dust should be a list"
    assert len(results["zombies"]) == 0, f"Expected 0 zombie accounts, but found {len(results['zombies'])}"
    assert results.get("total_sol_recoverable") == 0.0, f"Expected 0.0 recoverable SOL, but found {results.get('total_sol_recoverable')}"
    
    print("✅ Test Passed: Clean wallet correctly identified with no zombies.")


# --- Test Case 2: The Wallet with Trapped Liquidity ---
@pytest.mark.asyncio
async def test_sniff_wallet_with_zombie(async_client: AsyncClient):
    """
    Tests the Sniffer against our specific test wallet from `test_wallet.json`,
    which is known to have at least one zombie account created by `setup_test_wallet.py`.
    """
    print("\n--- Running Test: Wallet with Trapped Liquidity ---")
    
    # ARRANGE: Set up the test conditions
    # This is the public key for the wallet generated by `setup_test_wallet.py`
    wallet_with_zombie_pubkey = Pubkey.from_string("EiWfGmGbEqQJNPjbvuGmivXVSvrkftiVokgyqVbb6abM")
    sniffer = Sniffer(async_client, RPC_URL)

    # ACT: Perform the action we are testing
    results = await sniffer.sniff_accounts(wallet_with_zombie_pubkey)

    # ASSERT: Verify that the outcome is as expected
    assert results is not None, "Sniffer should return a result object, not None"
    assert isinstance(results.get("zombies"), list), "Zombies should be a list"
    assert len(results["zombies"]) > 0, f"Expected at least 1 zombie account, but found {len(results['zombies'])}"
    assert results["zombies"][0] == "6uVdRspPeGCByo6Rb4VMdmoYY7kptqacY6zRrB4sbmGH", "The known zombie account was not found in the results"
    assert results.get("total_sol_recoverable") > 0.0, f"Expected > 0.0 recoverable SOL, but found {results.get('total_sol_recoverable')}"
    
    print("✅ Test Passed: Trapped liquidity (zombie account) was correctly identified.")

# To run these tests, navigate to the `backend/` directory and run the command:
# pytest -v -s # The -s flag shows print statements
